[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.1.0"
description = "FastAPI Backend"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
include = ["app*"] 